const d = 'fsadf'

const a = {
    arrowParens: 'always',
    bracketSameLine: false,
    bracketSpacing: true,
    semi: true,
    experimentalTernaries: false,
    singleQuote: true,
    jsxSingleQuote: false,
    quoteProps: 'as-needed',
    trailingComma: 'all',
    singleAttributePerLine: false,
    htmlWhitespaceSensitivity: 'css',
    vueIndentScriptAndStyle: false,
    proseWrap: 'preserve',
    insertPragma: false,
    printWidth: 80,
    requirePragma: false,
    tabWidth: 5,
    useTabs: false,
    embeddedLanguageFormatting: 'auto',
    rangeStart: 0,
    rangeEnd: 0,
    cursorOffset: 0,
}
